applicaster/Zapp-Frameworks

plugins/zapp-generic-chromecast/manifests/manifest.config.js

This PR removes the screen flag in the Chromecast QB plugin manifest, as it mistakenly sets the plugin as a screen plugin every new push

fix: update chromecast manifest.config.js to not be screen

---

plugins/zapp-generic-chromecast/manifests/manifest.config.js

there is an error in the manifest because `npm_dependencies` field isn't wrapped in an array as it should be, and it is causing some builds to fail.
This change doesn't require an new push - I fixed the manifest in Zapp already

fix: correct npm_dependencies in manifest

---

plugins/zapp-generic-chromecast/apple/ZappChromecast.podspec.json
plugins/zapp-generic-chromecast/manifests/manifest.config.js
plugins/zapp-generic-chromecast/package.json

This PR fixes several problems which occured when transitioning the chromecast plugin to the new repo:
- "files" property was missing in the package.json. as a result, non js files were omitted when pushing to npm
- the package had direct dependencies to RN 59
- the manifest was referencing properties for tvos which it doesn't support
- the manifest.config file was adding the extra_dependencies properties for iOS on android platforms as well. as a result, this crashed builds on android (since android uses `extra_dependencies` field as well, but giving it a podspec path generates an error)

fix: fix chromecast plugin

---

plugins/zapp-apple/apple/universal/Helpers/Styles/StylesHelper.swift

[ZPP-2784](https://applicaster.atlassian.net/browse/ZPP-2784) - [Styling] loading_spinner_color key is not taking effect in the app
[ZPP-2785](https://applicaster.atlassian.net/browse/ZPP-2785) - [Styling] loading_error_label key is not taking effect in the app

fix for ZPP-2784, ZPP-2785 - [Styling] color keys are not taking effect in the app

---

plugins/quick-brick-xray/src/console.ts

React Native's console polyfill only handles invoking `console.error` with a string or an `Error` object, unlike the browser API, which accepts any arguments.
As a result, when XRay is sending events to the console (because the native module isn't available), the RN app will show the Red Box screen with `console.error [Object object]`, and won't send the payload to chrome.
In order to address this, the proxy for sending event to the console now has the following logic:
- if the log level is error, a warning will be sent with the entire event data, adding `Error:: ` to the event message. This will be properly displayed in the console
- on top of the this, console.error is invoked with an `Error` object constructed with the message of the event. this will show in RN's red box.

fix: send errors as warning on react-native console

---

package.json
yarn.lock

This PR adds a resolution field in the workspace's package.json
This is useful to make sure certain versions of dependencies are used, especially when there are reports of vulnerabilities

chore: add resolutions to workspace

---

plugins/video_subscriber_sso_apple/src/SSOProvider.js

This PR solves a crash which happens when login plugin isn't found.

fix: prevent crash when loginPlugin is undefined

---

package.json
plugins/quick-brick-xray/src/console.ts
plugins/quick-brick-xray/src/index.ts
plugins/quick-brick-xray/src/logLevels.ts
plugins/quick-brick-xray/src/utils.ts
plugins/quick-brick-xray/src/xray.ts
plugins/quick-brick-xray/types/index.d.ts
yarn.lock

This PR adds a method to sanitize arguments sent through the bridge so that functions and react components sent to Xray native are not crashing the app
It also includes a small fix to avoid confusions & issues between our warning method and the console's `warn` method, plus patches for vulnerabilities

feat: sanitize event data in Xray

---

plugins/quick-brick-xray/manifests/manifest.config.js

Now Apple frameworks declare x-ray npm dependency. Android still needs it to be installed if plugin ins in use.

Fix: add @applicaster/x-ray as extra_npm_dependencies for android platofrms

---

plugins/zapp-generic-chromecast/manifests/manifest.config.js

Currently the Chromecast plugin is marked as a preload. 
It is a mistake (you cannot use Chromecast as a hook of course)

fix(chromecast): Update manifest and mark the plugin as preload: false

---

plugins/video_playing_now_apple/manifests/manifest.config.js
plugins/zapp-apple/apple/universal/Plugins/PlayerDependant/PlayerDependantPluginsManager.swift

1. remove enable param as not really needed
2. update player dependent plugins initialization to use existing instances if exists

chore: Update Player dependent plugins to use existing instances if exists

---

.circleci/config.yml
.gitignore
jest.config.js
package.json
plugins/quick-brick-xray/README.md
plugins/quick-brick-xray/__mocks__/react-native.js
plugins/quick-brick-xray/__tests__/bootstrap.ts
plugins/quick-brick-xray/__tests__/event.test.ts
plugins/quick-brick-xray/__tests__/logger-native.test.ts
plugins/quick-brick-xray/__tests__/logger.test.ts
plugins/quick-brick-xray/__tests__/reactComponents.tsx
plugins/quick-brick-xray/src/Event.ts
plugins/quick-brick-xray/src/console.ts
plugins/quick-brick-xray/src/index.ts
plugins/quick-brick-xray/src/logger.ts
plugins/quick-brick-xray/src/utils.ts
plugins/quick-brick-xray/src/xray.ts
plugins/quick-brick-xray/types/index.d.ts
yarn.lock

This PR makes the `@applicaster/quick-brick-xray` safer to use by preventing it to crash when pushing logs.
It also adds tests which are running on CI
with this, js tests can be used on any plugin in the repository

fix: Better guarding in qb xray logs

---

plugins/quick-brick-xray/__tests__/logger-native.test.ts
plugins/quick-brick-xray/__tests__/logger.test.ts
plugins/quick-brick-xray/src/index.ts
plugins/quick-brick-xray/src/utils.ts

This PR changes the way context properties are sanitizes, by doing it when context is assigned, instead of doing it when events are sent

fix: proper sanitizing of context properties

---

plugins/applicaster-iap-framework/android/iap-rn/src/main/java/com/applicaster/iap/reactnative/utils/PurchasePromiseListener.kt
plugins/applicaster-iap-framework/android/iap-uni/src/main/java/com/applicaster/iap/uni/amazon/AmazonBillingImpl.kt
plugins/applicaster-iap-framework/android/iap-uni/src/main/java/com/applicaster/iap/uni/amazon/ReceiptStorage.kt

Unlike Google, Amazon only needs recieptId.

fix: Amazon only needs receiptId

---

plugins/zapp-push-plugin-firebase/android/build.gradle
plugins/zapp-push-plugin-firebase/android/src/main/java/com/applicaster/firebasepushpluginandroid/factory/DefaultNotificationFactory.kt
plugins/zapp-push-plugin-firebase/android/src/main/java/com/applicaster/firebasepushpluginandroid/factory/NotificationFactory.kt
plugins/zapp-push-plugin-firebase/android/src/main/java/com/applicaster/firebasepushpluginandroid/notification/NotificationUtil.kt
plugins/zapp-push-plugin-firebase/android/src/main/java/com/applicaster/firebasepushpluginandroid/services/APMessagingService.kt
plugins/zapp-push-plugin-firebase/manifests/manifest.config.js

Workaround for https://github.com/Kotlin/kotlinx.coroutines/issues/2041
That occured when SDK Core coroutines library was udpated to lates version to it can pass lint, because old version had another bug.
Coroutines were removed in the problematic place, all work is done in background thread provided by the Firebase.

fix: workaround for coroutines bug

---

plugins/session-storage-idfa/apple/ZappSessionStorageIdfa.podspec.json

set platform min version for legacy and qb

fix: set platform min version for legacy and qb

---

plugins/video_playing_now_apple/apple/tvos/ZPAppleVideoNowPlayingInfo+PlayerObserverProtocol.swift
plugins/video_playing_now_apple/apple/tvos/ZPAppleVideoNowPlayingInfo.swift

1. Fix support identifiers not only Int -> String and all that support protocol (NSCopying & NSObjectProtocol)
2. Add support if Entry.Extension.isLive use key `AVKitMetadataIdentifierServiceIdentifier`, otherwise `AVKitMetadataIdentifierExternalContentIdentifier`
3. Set progress if Entry.Extension.isLive skip, otherwise use identifier `AVKitMetadataIdentifierPlaybackProgress`
4. Progress will be updated from 0 -> 1 with step 0.01
According documentation: https://help.apple.com/itc/tvpumcstyleguide/#/itc0c92df7c9

fix: play now events

---

plugins/quick-brick-google-ima-apple/manifests/manifest.config.js

this PR sets the `react-native: true` flag on the plugin manifest.
Leaving this to false prevents the JS hook which grabs the config from the UI builder and passes to the playable item to be installed and run properly.

fix: enable IMA js hook

---

plugins/quick-brick-google-ima-apple/manifests/manifest.config.js

This PR adds the dependency_name and dependency_version properties in the google IMA manifest, which are also required to use the JS hook in this plugin

fix: add dependency name & version to IMA manifest

---

plugins/quick-brick-apple-user-activity/apple/Universal/Bridge/AppleUserActivityBridge.swift
plugins/quick-brick-apple-user-activity/manifests/manifest.config.js
plugins/quick-brick-apple-user-activity/src/AppleUserActivity.ts
plugins/quick-brick-apple-user-activity/src/index.ts

this PR refactors the apple user activity feature to rely on the new screen hook API instead of the player hook.
it also changes the name of the extension used for this.
Can be tested with the beta version of the plugin created, and the [version coming soon] canary of QB;

refactor: use new screen hook API

---

plugins/zapp-push-plugin-firebase/apple/extensions/service/NotificationService.swift
plugins/zapp-push-plugin-firebase/manifests/manifest.config.js

adding support for custom sounds on firebase push notifications
scenarios:
1. parameter not added -> default behaviour
2. parameter added, sound file not exists -> push default sound
3. parameter added, sound file exists -> custom sound

feat: adding support for custom sounds on firebase push notifications

---

plugins/quick-brick-xray/android/src/main/java/com/applicaster/plugin/xray/TimingSink.kt
plugins/quick-brick-xray/android/src/main/java/com/applicaster/plugin/xray/XRayPlugin.kt
plugins/quick-brick-xray/android/src/main/java/com/applicaster/plugin/xray/model/Settings.kt
plugins/quick-brick-xray/android/src/main/java/com/applicaster/plugin/xray/ui/fragements/SettingsFragment.kt
plugins/quick-brick-xray/android/src/main/res/layout/xray_fragment_settings.xml
plugins/quick-brick-xray/android/src/main/res/values/strings.xml

Added an option to share csv file with log messages intervals right away from the app.
This allow convenient flow to basic load time profiling:
- enable the timing logging sink
- restart the app to obtain new data
- go to xray screen and use Share button to send data to the gmail (Google Drive is not smart enough to import csv file as sheets). The file is also available on the SD card directly in the application Files directory, for example /sdcard/Android/data/com.applicaster.miamiheat/files/profile.csv.
- in gmail, file can be checked right away as a preview, or exported to Google Sheets for advanced filtering
While it does not provide timings for every operation, as stopwatch type of timing would do (we see how much time has passed before current line was logged, not time taken by the …

feat: timing csv sink

---

plugins/quick-brick-google-ima-apple/apple/universal/GoogleInteractiveMediaAdsAdapter/GoogleInteractiveMediaAdsAdapter.swift

Pause player before going to fetch the preroll (if preroll exists)

fix: Pause player before going to fetch the preroll (if preroll exists)

---

plugins/quick-brick-google-ima-apple/apple/universal/GoogleInteractiveMediaAdsAdapter/GoogleInteractiveMediaAdsAdapter+QBPlayerObserverProtocol.swift
plugins/quick-brick-google-ima-apple/apple/universal/GoogleInteractiveMediaAdsAdapter/GoogleInteractiveMediaAdsAdapter.swift
plugins/quick-brick-google-ima-apple/manifests/manifest.config.js
plugins/zapp-apple/apple/universal/Plugins/PlayerDependant/PlayerDependantPluginsManager+PlayerObserverProtocol.swift
plugins/zapp-apple/apple/universal/Plugins/PlayerDependant/PlayerDependantPluginsManager.swift
plugins/zapp-apple/apple/universal/RootController/FacadeConnector/RootController+FacadeConnectorPlayerDependantProtocol.swift
plugins/zapp-core/apple/universal/Plugins/Player/PlayerObserverProtocol.swift

1. Adding readyToPlay function to the connector to perform changes on the player dependent plugins before starting to play
2. Changes in IMA to use it for ads before playback
@kononenkoAnton  this is instead of moving the IMA into the player because of IDFA usage in IMA which should not be a part of default implementation as it could be used by kids apps

feat: Adding readyToPlay function to the player + Changes in IMA to use it for ads before playback

---

plugins/quick-brick-xray/manifests/manifest.config.js
plugins/zapp-analytics-plugin-adobe/manifests/manifest.config.js
plugins/zapp-analytics-plugin-akamai/manifests/manifest.config.js
plugins/zapp-analytics-plugin-appsflyer/manifests/manifest.config.js
plugins/zapp-analytics-plugin-chartbeat/manifests/manifest.config.js
plugins/zapp-analytics-plugin-comscore/manifests/manifest.config.js
plugins/zapp-analytics-plugin-cooladata/manifests/manifest.config.js
plugins/zapp-analytics-plugin-firebase/manifests/manifest.config.js
plugins/zapp-analytics-plugin-google/manifests/manifest.config.js
plugins/zapp-analytics-plugin-mixpanel/manifests/manifest.config.js
plugins/zapp-push-plugin-firebase/manifests/manifest.config.js
plugins/zapp_local_notifications/manifests/manifest.config.js
templates/manifests/manifest.config.js

We have a flag telling that the plugin is a hook enabled for plugins that are not hooks.
Template manifest was updated for convenience.

feat: disable preload hook flag for plugins that do not need it

---

plugins/applicaster-iap-framework/android/iap-rn/src/main/java/com/applicaster/iap/reactnative/IAPBridge.kt
plugins/applicaster-iap-framework/android/iap-rn/src/main/java/com/applicaster/iap/reactnative/utils/AcknowledgePromiseListener.kt
plugins/applicaster-iap-framework/android/iap-rn/src/main/java/com/applicaster/iap/reactnative/utils/ConsumePromiseListener.kt
plugins/applicaster-iap-framework/android/iap-rn/src/main/java/com/applicaster/iap/reactnative/utils/FinishingPurchasePromiseListener.kt
plugins/applicaster-iap-framework/android/iap-rn/src/main/java/com/applicaster/iap/reactnative/utils/PromiseListener.kt
plugins/applicaster-iap-framework/android/iap-rn/src/main/java/com/applicaster/iap/reactnative/utils/PurchasePromiseListener.kt
plugins/applicaster-iap-framework/android/iap-rn/src/main/java/com/applicaster/iap/reactnative/utils/RestorePromiseListener.kt
plugins/applicaster-iap-framework/android/iap-rn/src/main/java/com/applicaster/iap/reactnative/utils/SKUPromiseListener.kt
plugins/applicaster-iap-framework/android/iap-uni/build.gradle
plugins/applicaster-iap-framework/android/iap-uni/consumer-rules.pro
plugins/applicaster-iap-framework/android/iap-uni/proguard-rules.pro
plugins/applicaster-iap-framework/android/iap-uni/src/main/java/com/applicaster/iap/uni/amazon/AmazonBillingImpl.kt

Before we were relying on RN to log events, now native layer logs these as well.

feat: add logs and proguard rules to in-app purchasees

---

plugins/applicaster-iap-framework/android/iap-rn/src/main/java/com/applicaster/iap/reactnative/IAPBridge.kt
plugins/applicaster-iap-framework/android/iap-uni/src/main/java/com/applicaster/iap/uni/amazon/AmazonBillingImpl.kt

Amazon Live Testing returns null prices, and its not handled in calling code. Now we substitute these with empty string for null safety.
All IAP calls were moved to UI thread for safety.
A lot of logging was added for diagnostics.

Feat: Amazon fix and logs

---

plugins/zapp_login_plugin_oauth_2_0/manifests/manifest.config.js

In **zapp_login_plugin_oauth_2_0** added the ability to configure the display of the navbar if the plugin does not open as a pre-hook

fix: added "allow_screen_plugin_presentation" flag to the manifest

---

plugins/zapp-analytics-plugin-segment/android/src/main/java/com/applicaster/analytics/segment/SegmentAgent.kt

Android SDK expects different plugin param key name and separator for filtered events.
iOS seems to parse the values inside the plugin, so same logic was added to the Android in order to not break the compatibility. Later we need to rename the field.
Also, SDK should use en locale lowercase

fix: wrong ignore key name

---

localProject/apple/FrameworksApp.xcodeproj/project.pbxproj
plugins/applicaster-di-manager/android/src/main/java/com/applicaster/plugin/dimanager/DIManager.kt
plugins/applicaster-di-manager/apple/Podfile
plugins/applicaster-di-manager/apple/tests/Dummy.swift
plugins/applicaster-di-manager/package.json

On iOS token was recently move from LocalStorage to SessionStorage, but Android was not updated.
It actually rises a lot of questions on what we will do in the offline mode, when user will go back online (some random parts of the app won't work for no visible reasons). We can't make token request on demand since we use storage to communicate (only if we will wrap it on RN and introduce bridge or do something like OnDeviceOnline handlers)

fix: move DI data to SessionStorage

---

plugins/zapp-react-native-theo-player/android/build.gradle
plugins/zapp-react-native-theo-player/android/src/main/java/com/theoplayerreactnative/events/AdEventMapper.kt
plugins/zapp-react-native-theo-player/package.json

Ads events added:
- onAdBreakBegin
-  timeOffset: int
- maxDuration: int
- maxRemainingDuration: int
- integrationKind: string
- breakSize: int (how many ads inside)
- onAdBreakEnd
- same as above
- onAdBegin (id: String?)
- id: String?
- type: string?
- duration: Int? (for LinearAd)
- creativeId: String? (for Google IMA)
- adSystem: String? (for Google IMA)
- resourceURI: String? (for NonLinearAd)
- breakSize: int (how many ads parent ad block has)
- adPosition: int
- onAdEnd (id: String?)
- same as above
- onAdError
- same as above
- error: string
More data can be added if needed:
https://docs.theoplayer.com/api-reference/android/index.html
Need to add these events to QB docs, analytics and analytics documentation.
- https://docs.google.com/spreadsheets/d/1Rff5f1-Bbdrf_lTv-u-j_Iws-nWU-DM …

feat: add theo ads events

---

plugins/quick-brick-xray/android/src/main/java/com/applicaster/plugin/xray/logadapters/APLoggerAdapter.kt

IAPLogger allows to pass null as Throwable, while xray IEventBuilder does not, so we must handle it in wrapper.

fix: allow null throwable since interface java allows it

---

plugins/quick-brick-opta-stats/android/src/main/java/com/applicaster/opta/statsscreenplugin/OptaStatsActivity.kt
plugins/quick-brick-opta-stats/android/src/main/java/com/applicaster/opta/statsscreenplugin/reactnative/OptaStatsViewManager.kt

Suppressing wrong ReactNative root view context bugs (it uses app context instead of Activity).

Fix react context

---

plugins/applicaster-cmp-didomi/android/src/main/java/com/applicaster/plugin/didomi/DidomiPlugin.kt
plugins/applicaster-cmp-didomi/manifests/manifest.config.js

Didomi does not support remote URL logos on mobile (they actually fetch it, but have incomplete implementation for displaying).
And web console does not allows to input drawable resource name (it requires URL), but it can be overridden manually in Didomi console.
We add an upload option and validation code for that flow

feat: didomi logo

---

plugins/applicaster-cmp-didomi/android/src/main/java/com/applicaster/plugin/didomi/DidomiPlugin.kt

I have an integrity check for logo, but there is a race condition, onReady can arrive before Didomi updates the logo resource. User does not really care about the sequence, and showNotice is not called from RN, only on the start, so I can just move the check to the point after notice was presented

fix: better didomi setup validation

---

plugins/zapp-push-plugin-firebase/android/src/main/java/com/applicaster/firebasepushpluginandroid/FirebasePushProvider.kt
plugins/zapp-push-plugin-firebase/android/src/main/java/com/applicaster/firebasepushpluginandroid/services/APMessagingService.kt
plugins/zapp-push-plugin-firebase/manifests/manifest.config.js

Support for localized default topics added.
Also we now keep track of topics that we 'own', i.e. register by default. If something got changed due to locale change or configuration update in Zapp, change will be propagated: removed topics will be unsubscribed from, and new one will be subscribed to.

feat: localized default topics

---

plugins/first-time-user-expirience-screen/src/Components/FirstTimeUserExpirience/index.tsx

This PR is just adding a small override for Android tablets, we are using the SafeAreaView which adds padding to the top and bottom of the view, but we only need it on the bottom in this case so we are just making a minor css change in this PR.
We believe that after [this change](https://github.com/applicaster/QuickBrick/pull/2220) library is correctly adding padding to the top and the bottom of the screen so that we fit the screen and make space for software buttons and status bar.
This PR heavily relies on the changes to the SafeAreaView library in QuickBrick, otherwise the fix won't work.

fix: override safeareaview padding if android tablet

---

plugins/quick-brick-opta-stats/src/index.js

Example url passing on android:
`adb shell am start -a "android.intent.action.VIEW" -d "ca2019://present?screen_id=082ac1b2-783f-4f41-b95a-f4a486a4acd6\&type=all_matches_screen\&team_id=ajab3nmpoltsoeqcuoyi4pwzx"`
Known bug: if app is already on COPA screen, navigation to modal ones won't happen, since QB navigation checks screen ID.
This requires QB update.
I also found high level hooks in RN, we can just register there.
`adb shell am start -a "android.intent.action.VIEW" -d "ca2019://copa_stats?screen_id=082ac1b2-783f-4f41-b95a-f4a486a4acd6\&type=all_matches_screen\&team_id=ajab3nmpoltsoeqcuoyi4pwzx"`
No QB update required for this option.

feat: pass url to native

---

plugins/applicaster-account-components/src/index.js

Inplayer is causing build failures because of one of its dependencies. 
To fix the second issue related to the applicaster-account-components we just had to change out the component was being exported.

fix: applicaster account components export

---

plugins/quick-brick-inplayer-login/manifests/manifest.config.js
plugins/quick-brick-inplayer-login/package.json

Inplayer is causing build failures because of one of its dependencies. 
@applicaster/applicaster-account-components is using fancy JS that needs to be transpiled:
```
ERROR in /home/circleci/zapp-webOS/node_modules/@applicaster/applicaster-account-components/src/Components/AccountFlow/index.js 20:34
Module parse failed: Unexpected token (20:34)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|   return {
|     ...container,
>     backgroundColor: screenStyles?.background_color,
|   };
| };
```
One way to get around that is by adding it to the excludedNodeModules list. 
That's what I did in this PR, we will need to do a fix in the account components plugin as well, or in the …

fix: inplayer deps bumped

---

plugins/zapp-push-plugin-firebase/android/src/main/java/com/applicaster/firebasepushpluginandroid/services/APMessagingService.kt

Skip notifications that belongs to the event where at least one was already displayed.
Tags field is used for now. I also store current time for first time event was handled, so later we can add timeouts.

feat: skip notification belonging to already displayed events (tags)

---

plugins/zapp-react-native-theo-player/android/src/main/java/com/theoplayerreactnative/SourceHelper.java

there was no handling for drm key to be present put null. This code was taken from the example and never actually checked for edge cases. Now we do check

fix: drm key can be null

---

plugins/zapp-push-plugin-firebase/android/src/main/java/com/applicaster/firebasepushpluginandroid/services/APMessagingService.kt

Firebase should collapse notifications with the same tag, but it must be implemented manually for data and foreground messages

feat: tag notification replace support

---

plugins/zapp-generic-chromecast/src/CastHandler/CastHandler.js

We got a problem with sending a media item to be casted to the native module, media item object is default and does not fit for us, because customer's Chromecast receiver player expects additional specific data. 
Expected ZappN metadata should had at least following params (sample from old native impl):
`mediaItem = {isPlayer=true, title=EURO - Die Teams, description=, mediaUrl=vas://puls4-at, isLive=true, streamDuration=0, playPosition=0, customData={"country":"at","clipId":"134"}}`
We implemented hook that fill all these values and need to update the cast handler to pull this properties and send them to chromecast.
[Monday ticket](https://applicaster.monday.com/boards/1141653998/pulses/1352485463?userId=17198506)

fix: chromecast mediaItem

---

plugins/zapp-generic-chromecast/android/src/main/java/com/reactnative/googlecast/GoogleCastModule.java
plugins/zapp-generic-chromecast/apple/ios/Bridge/Chromecast/ChromecastManagerBridge.swift
plugins/zapp-generic-chromecast/apple/ios/Bridge/Chromecast/ChromecastManagerBridgeExport.m
plugins/zapp-generic-chromecast/apple/ios/Extensions/ChromecastAdapter+ChromecastProtocol.swift

We want to add a new native module to the Chromecast plugin that gives the currently connected device metadata. 
This enables us to create custom Chromecast views in react native.
The current metadata that will be available is:
* deviceID
* deviceVersion
* friendlyName
* modelName
In the future, we would be able to add more params such as volume and more.

feat(Chromecast-Plugin): add a method to get the cast connected device e info

---

plugins/zapp-analytics-plugin-gemius/android/proguard-rules.pro

Proguard rules are not picked up by gradle from aar libraries linked to plugin libraries projects.
Copy the rules for now to the plugin library level.

fix: copy proguard rules from aar

---

plugins/zapp-apple/apple/ZappApple.podspec.json
plugins/zapp-apple/apple/universal/Helpers/Reachability/ReachabilityManager.swift
plugins/zapp-apple/apple/universal/Helpers/Reachability/ReachabilityManagerDelegate.swift
plugins/zapp-apple/apple/universal/RootController/FacadeConnector/RootController+FacadeConnectorConnectivityProtocol.swift
plugins/zapp-apple/apple/universal/RootController/RootController+ReachabilityManagerDelegate.swift
plugins/zapp-apple/apple/universal/RootController/RootController.swift

adding support for Network framework instead of Reachability
Apple’s Network framework provides a number of useful classes for working with network data, including one specifically designed to monitor network accessibility: NWPathMonitor. If you ever used Apple’s older Reachability system, NWPathMonitor replaces it fully.
https://www.hackingwithswift.com/example-code/networking/how-to-check-for-internet-connectivity-using-nwpathmonitor

feat: adding support for Network framework instead of Reachability

---

plugins/zapp-apple/apple/universal/RootController/RootController.swift

prepare plugins after finishing splash presentation

fix: prepare plugins after finishing splash presentation

---

plugins/zapp-analytics-plugin-gemius/apple/universal/GemiusAnalytics+ScreenEvents.swift

If value is empty, Genius SDK crashing the app

bug: fix genius analytics crash

---

plugins/applicaster-account-components/src/Utils/Customization/index.js
plugins/quick-brick-inplayer-login/package.json

This PR addresses a small issue that was causing the applicaster-account-component screen... used by InPlayer Login screen to crash. The issue was that we were utilizing a method that did not exist.
Was going to include this UI change in this PR but I think its best that we just merge this fix.
https://scene.zeplin.io/project/6088402e4a714f01ede68d7b/screen/608844ade4311706261892eb

fix: mapKeyToStyle was refering to a method that didn't exist

---

plugins/applicaster-cmp-didomi/manifests/manifest.config.js
plugins/applicaster-cmp-onetrust/manifests/manifest.config.js
plugins/applicaster-di-manager/apple/universal/ZPDiManager.swift
plugins/applicaster-di-manager/manifests/manifest.config.js
plugins/remote-info-to-session-storage/apple/universal/ZPRemoteInfoToSessionStorage.swift
plugins/remote-info-to-session-storage/manifests/manifest.config.js
plugins/zapp-core/apple/universal/PluginModel/ZPPluginModel.swift

refactor to plugin subtypes to get the subtype string from api on plugin manifest and not rely on identifier substring

fix: refactor to plugin subtypes to get the subtype string from api

---

plugins/zapp-react-native-theo-player/android/src/main/java/com/theoplayerreactnative/TheoPlayerViewManager.java

Disabling ad preload as THEO team suggested to prevent stalls on broken ads.

fix: disable Ad preload to workaround Ad bugs

---

plugins/zapp_login_plugin_oauth_2_0/src/Components/OAuth.js
plugins/zapp_login_plugin_oauth_2_0/src/Services/OAuth2Service/index.js

This PR fixes an issue with the way the token is saved in the oauth 2 plugin.
it was failing to retrieve the key from plugin configuration, and then didn't pass the key to the function saving the data in storage.
as a result, the key was always set in the default access_token property

fix: proper setting of storage keys

---

plugins/zapp-analytics-plugin-gemius/android/src/main/java/com/applicaster/analytics/gemius/GemiusAgent.kt
plugins/zapp-analytics-plugin-gemius/android/src/main/java/com/applicaster/analytics/gemius/PlayerAdapter.kt
plugins/zapp-analytics-plugin-gemius/android/src/main/java/com/applicaster/analytics/gemius/ScreenAdapter.kt
plugins/zapp-analytics-plugin-gemius/android/src/main/java/com/applicaster/analytics/gemius/adapters/AnalyticsPlayerAdapter.kt
plugins/zapp-analytics-plugin-gemius/android/src/main/java/com/applicaster/analytics/gemius/adapters/AnalyticsScreenAdapter.kt
plugins/zapp-analytics-plugin-gemius/android/src/main/java/com/applicaster/analytics/gemius/adapters/IAnalyticsAdapter.kt

Fixing Gemius events:
- excessive Play events
- report ad break for mid-rolls only (will also report for post rolls, since event data is not passed from RN)

Fix gemius events

---

plugins/zapp-generic-chromecast/apple/ios/Extensions/ChromecastAdapter+ChromecastProtocol.swift

Related task: https://applicaster.monday.com/boards/1141653998/pulses/1512956447.
Behaviour before fix:
https://drive.google.com/file/d/1j-lu_VwtpRVv4xIqdZHz4HYSpxvnhhF8/view
Behaviour after fix:
https://user-images.githubusercontent.com/76045389/127443026-5a54b813-66d2-45c3-9f1b-51189ac5c334.mov

fix: added ability to use several chromecast buttons for zapp-generic-chromecast

---

plugins/quick-brick-native-apple/apple/ios/ReactNativeEventEmitter.swift

Fix to sending first change-orientation even even in case initial orientation=unknown

fix: send first change-orientation event even for unknown orientation

---

plugins/quick-brick-xray/android/src/main/java/com/applicaster/plugin/xray/logadapters/APLoggerAdapter.kt

Extended detail were not added to xray error messages on APLoggerAdapter

fix: add details on xray error log
