applicaster/Zapp-Frameworks

plugins/zapp-apple/apple/universal/Helpers/SwiftUtils/SwiftUtils.swift

remove not used code of fetching idfa

chore(idfa) - remove not used code of fetching idfa

---

plugins/zapp-apple/apple/universal/Helpers/TrackingManager/TrackingManager.swift
plugins/zapp-apple/apple/universal/Helpers/XrayLogger/Templates/PlayerDependantPluginsManager/PlayerDependantPluginsManangerLogs.swift
plugins/zapp-apple/apple/universal/Helpers/XrayLogger/Templates/PluginsManager/AnalyticsPluginsManager/AnalyticsPluginsManagerLogs.swift
plugins/zapp-apple/apple/universal/Helpers/XrayLogger/Templates/PluginsManager/PlayerDependantPluginsManager/PlayerDependantPluginsManangerLogs.swift
plugins/zapp-apple/apple/universal/Helpers/XrayLogger/Templates/PluginsManager/PluginsManagerControlFlowLogs.swift
plugins/zapp-apple/apple/universal/Helpers/XrayLogger/Templates/PluginsManager/PluginsManagerHookHandlerLogs.swift
plugins/zapp-apple/apple/universal/Helpers/XrayLogger/Templates/PluginsManager/PluginsManagerLogs.swift
plugins/zapp-apple/apple/universal/Helpers/XrayLogger/Templates/PluginsManager/PushPluginsManager/PushPluginsManagerLogs.swift
plugins/zapp-apple/apple/universal/Helpers/XrayLogger/Templates/TrackingManagerLogs.swift
plugins/zapp-apple/apple/universal/Plugins/Analytics/AnalyticsManager.swift
plugins/zapp-apple/apple/universal/Plugins/PlayerDependant/PlayerDependantPluginsManager.swift
plugins/zapp-apple/apple/universal/Plugins/PluginManager/PluginsManager+ControlFlow.swift
plugins/zapp-apple/apple/universal/Plugins/PluginManager/PluginsManager+HookHandler.swift
plugins/zapp-apple/apple/universal/Plugins/PluginManager/PluginsManager.swift
plugins/zapp-apple/apple/universal/Plugins/PushPluginsManager/PushPluginsManager.swift
plugins/zapp-apple/apple/universal/RootController/RootController.swift

chore(logs) - Adding more logs

---

plugins/zapp-apple/apple/universal/Plugins/PlayerDependant/PlayerDependantPluginsManager+PlayerAdObserverProtocol.swift
plugins/zapp-apple/apple/universal/RootController/FacadeConnector/RootController+FacadeConnectorPlayerDependantProtocol.swift
plugins/zapp-core/apple/universal/FacadeConnector/Protocols/FacadeConnectorPlayerDependantProtocol.swift
plugins/zapp-core/apple/universal/Plugins/Player/PlayerAdObserverProtocol.swift

https://applicaster.atlassian.net/browse/IM-832
add ability to send to the PlayerDependent plugins also Ad event with a new "PlayerAdObserverProtocol"

add PlayerAdObserverProtocol

---

plugins/video_subscriber_sso_apple/src/Components/Account/Components/AlertActions/index.js
plugins/video_subscriber_sso_apple/src/SSOProvider.js

Fix crash if no plugin, remove fallback login from settings alert If not defined

---

plugins/quick-brick-google-ima-apple/apple/universal/GoogleInteractiveMediaAdsAdapter/GoogleInteractiveMediaAdsAdapter.swift
plugins/quick-brick-google-ima-apple/apple/universal/GoogleInteractiveMediaAdsAdapter/GoogleInteractiveMediaAdsAdapterTrackingIdentifier.swift
plugins/quick-brick-google-ima-apple/apple/universal/GoogleUrlTagData/GoogleUrlTagData.swift
plugins/quick-brick-google-ima-apple/apple/universal/GoogleUrlTagData/GoogleUrlTagDataKeys.swift
plugins/quick-brick-google-ima-apple/manifests/manifest.config.js

1. Removing not needed call to fetch the identifier
2. Adding support for TFUA
https://developers.google.com/interactive-media-ads/docs/sdks/ios/client-side/consent#tagging_users_as_under_the_age_of_consent

chore(ima) - Add support for TFUA

---

plugins/quick-brick-xray/android/src/main/java/com/applicaster/plugin/xray/XRayPlugin.kt
plugins/quick-brick-xray/android/src/main/java/com/applicaster/plugin/xray/ui/fragements/FileLogFragment.kt
plugins/quick-brick-xray/manifests/manifest.config.js
plugins/quick-brick-xray/package.json

Android TV and Amazon FireTV support added to X-Ray

Feat: add tv targets in manifest

---

plugins/quick-brick-xray/android/src/main/java/com/applicaster/plugin/xray/XRayPlugin.kt
plugins/quick-brick-xray/android/src/main/java/com/applicaster/plugin/xray/model/LogLevelSetting.kt
plugins/quick-brick-xray/android/src/main/java/com/applicaster/plugin/xray/model/Settings.kt
plugins/quick-brick-xray/android/src/main/java/com/applicaster/plugin/xray/ui/LogActivity.kt
plugins/quick-brick-xray/android/src/main/java/com/applicaster/plugin/xray/ui/fragements/SettingsFragment.kt
plugins/quick-brick-xray/android/src/main/res/layout/xray_fragment_settings.xml
plugins/quick-brick-xray/android/src/main/res/values/strings.xml

Add React Native Printer debug switch on settings screen
Fix some UI glitches
Add some hints

Feat: Update settings screen

---

plugins/applicaster-iap-framework/android/iap-rn/src/main/java/com/applicaster/iap/reactnative/utils/Wrappers.kt
plugins/applicaster-iap-framework/android/iap-uni/src/main/java/com/applicaster/iap/uni/amazon/AmazonBillingImpl.kt
plugins/applicaster-iap-framework/android/iap-uni/src/main/java/com/applicaster/iap/uni/amazon/ReceiptStorage.kt
plugins/applicaster-iap-framework/android/iap-uni/src/main/java/com/applicaster/iap/uni/api/Purchase.kt

Amazon User Id retrieved and added to purchase since looks like its needed for validation.

Feat: Add Amazon UserId

---

plugins/applicaster-iap-framework/android/iap-uni/src/main/java/com/applicaster/iap/uni/amazon/AmazonBillingImpl.kt
plugins/applicaster-iap-framework/android/iap-uni/src/main/java/com/applicaster/iap/uni/amazon/ReceiptStorage.kt

Handle flow when amazon purchase was done, but not marked as fulfilled (inplayer validation post failed)

Fix handle amazon not fulfilled

---

plugins/quick-brick-xray/README.md

Update x-ray README.md for URL Schemes

---

plugins/zapp-core/apple/ios/Universal/LocaNotifications/LocalNotificationResponseParser.swift
plugins/zapp-core/apple/universal/LocaNotifications/LocalNotificationPayloadConst.swift

Retrieve url param from local notification payload

feat(url) - Retrieve url param from local notification payload

---

plugins/zapp-generic-chromecast/apple/ZappChromecast.podspec.json
plugins/zapp-generic-chromecast/manifests/manifest.config.js

feat(ios14) - Chromecast updates for ios14

---

plugins/zapp-apple/apple/universal/Plugins/PushPluginsManager/PushPluginsManager.swift

fix(logger): save data as string

---

plugins/zapp-generic-chromecast/apple/ios/Extensions/ChromecastAdapter+ChromecastProtocol.swift

fix for chromecast changes in ios 14

fix(cc) - fix for chromecast changes in ios 14

---

plugins/quick-brick-xray/manifests/manifest.config.js
plugins/quick-brick-xray/package.json

chore: update xray to 0.0.15

---

plugins/zapp-generic-chromecast/android/src/main/java/com/reactnative/googlecast/GoogleCastModule.java

On devices without Google Play Services Chromecast plugin crashes in initialization sequence in CastContext.getSharedInstance, and the app never starts (crash is in the background thread).
Now we check if we can access the service.

Fix Chromecast crash when Google Services are absent

---

jest.config.js
plugins/quick-brick-xray/src/console.ts
plugins/quick-brick-xray/src/utils.ts

This PR fixes the way tests allow messages to be sent to the console in this repo only, as this causes issues when running tests in other repos

fix: properly allow tests to run in the repo\'s tests

---

plugins/zapp-apple/apple/universal/Helpers/LoggerAssistance/LoggerAssistanceManager.swift
plugins/zapp-apple/apple/universal/Helpers/SettingsBunlde/SettingsBundleHelper.swift
plugins/zapp-apple/apple/universal/Helpers/SwiftUtils/SwiftUtils.swift
plugins/zapp-apple/apple/universal/Helpers/UrlScheme/UrlSchemeHandler+settings.swift
plugins/zapp-apple/apple/universal/Helpers/UrlScheme/UrlSchemeHandler.swift
plugins/zapp-apple/apple/universal/Helpers/XrayLogger/Templates/LoggerAssistanceManagerLogs.swift
plugins/zapp-apple/apple/universal/RootController/RootController.swift

Add settings section parameters handling for logger assistance

feat: Add settings section parameters handling for logger assistance

---

plugins/video_playing_now_apple/apple/ZappAppleVideoNowPlayingInfo.podspec.json
plugins/video_playing_now_apple/apple/ios/NowPlayingLogger.swift
plugins/video_playing_now_apple/apple/ios/ZPAppleVideoNowPlayingInfo+PlayerObserverProtocol.swift
plugins/video_playing_now_apple/apple/ios/ZPAppleVideoNowPlayingInfo.swift
plugins/video_playing_now_apple/apple/universal/ZPAppleVideoNowPlayingInfoBase.swift

add logs and more events to now playing info

fix: Now playing info

---

plugins/quick-brick-xray/apple/Universal/QickBrickXray.swift

adding generation and fetching of single log file from multiple json files created for logs
related:
https://github.com/applicaster/x-ray/pull/37

feat: adding generation and fetching of single log file from multiple json files created for logs

---

plugins/quick-brick-apple-user-activity/apple/AppleUserActivity.podspec.json

fix: remove unused dependencies

---

plugins/quick-brick-xray/apple/Podfile
plugins/quick-brick-xray/apple/QuickBrickXray.podspec.json
plugins/quick-brick-xray/apple/Universal/Cells/LogLevelSelectCell/LogLevelSelectCell.swift
plugins/quick-brick-xray/apple/Universal/Cells/SwitchCell/SwitchCell.swift
plugins/quick-brick-xray/apple/Universal/Cells/SwitchCell/SwitchCellDelegate.swift
plugins/quick-brick-xray/apple/Universal/Extensions/LogLevel+ConfigurationKey.swift
plugins/quick-brick-xray/apple/Universal/KeysHelper.swift
plugins/quick-brick-xray/apple/Universal/QuickBrickXray+PluginURLHandlerProtocol.swift
plugins/quick-brick-xray/apple/Universal/QuickBrickXray+Settings.swift
plugins/quick-brick-xray/apple/Universal/QuickBrickXray.storyboard
plugins/quick-brick-xray/apple/Universal/QuickBrickXray.swift
plugins/quick-brick-xray/apple/Universal/Settings.swift
plugins/quick-brick-xray/apple/Universal/ViewControllers/LogLevelViewController/LogLevelOptions.swift
plugins/quick-brick-xray/apple/Universal/ViewControllers/LogLevelViewController/LogLevelViewController.swift
plugins/quick-brick-xray/apple/Universal/ViewControllers/SettingsViewController/SettingsHelper.swift
plugins/quick-brick-xray/apple/Universal/ViewControllers/SettingsViewController/SettingsViewController.swift
plugins/quick-brick-xray/apple/ios/QuickBrickXray+Shortcuts.swift
plugins/quick-brick-xray/manifests/ios.json
plugins/quick-brick-xray/manifests/ios_for_quickbrick.json
plugins/quick-brick-xray/manifests/manifest.config.js

chore: Renaming typo in Xray plugin

---

plugins/zapp-analytics-plugin-appsflyer/apple/ZappAnalyticsPluginAppsFlyer.podspec.json
plugins/zapp-analytics-plugin-appsflyer/apple/ios/APAnalyticsProviderAppsFlyer.swift
plugins/zapp-analytics-plugin-appsflyer/manifests/ios.json
plugins/zapp-analytics-plugin-appsflyer/manifests/ios_for_quickbrick.json
plugins/zapp-analytics-plugin-appsflyer/manifests/manifest.config.js
plugins/zapp-analytics-plugin-appsflyer/package.json
plugins/zapp-analytics-plugin-mixpanel/apple/ZappAnalyticsPluginMixpanel.podspec.json
plugins/zapp-analytics-plugin-mixpanel/apple/ios/APAnalyticsProviderMixpanel.swift
plugins/zapp-analytics-plugin-mixpanel/manifests/ios.json
plugins/zapp-analytics-plugin-mixpanel/manifests/ios_for_quickbrick.json
plugins/zapp-analytics-plugin-mixpanel/manifests/manifest.config.js
plugins/zapp-analytics-plugin-mixpanel/package.json

Moving Mixpanel and AppsFlyer plugins

BREAKING CHANGE: Moving Mixpanel and AppsFlyer plugins

---

plugins/zapp-push-plugin-firebase/android/build.gradle
plugins/zapp-push-plugin-firebase/android/src/main/AndroidManifest.xml
plugins/zapp-push-plugin-firebase/android/src/main/java/com/applicaster/firebasepushpluginandroid/FirebasePushProvider.kt

Disable auto start for messaging
Add support for run-time enable-disable operations for the plugin

feat: support disable for firebase push

---

plugins/zapp-analytics-plugins/apple/Podfile
plugins/zapp-analytics-plugins/apple/ZappAnalyticsPluginsSDK.podspec.json
plugins/zapp-analytics-plugins/apple/universal/ObjCFiles/APAnalyticsProvider.h
plugins/zapp-analytics-plugins/apple/universal/ObjCFiles/APAnalyticsProvider.m
plugins/zapp-analytics-plugins/apple/universal/ObjCFiles/ZPPlayerControllsNotifications.h
plugins/zapp-analytics-plugins/apple/universal/ObjCFiles/ZPPlayerControllsNotifications.m
plugins/zapp-analytics-plugins/apple/universal/TimedEventsSupport/ZPAnalyticsProvider+TimedEventsSupport.swift
plugins/zapp-analytics-plugins/apple/universal/TimedEventsSupport/ZPAnalyticsProviderTimedEventsSupportProtocol.swift
plugins/zapp-analytics-plugins/apple/universal/ZPAnalyticsProvider+AnalyticsProviderProtocol.swift
plugins/zapp-analytics-plugins/apple/universal/ZPAnalyticsProvider.swift
plugins/zapp-analytics-plugins/apple/universal/ZappAnalyticsPluginsSDK.h
plugins/zapp-analytics-plugins/package.json
plugins/zapp-push-plugins/apple/Podfile
plugins/zapp-push-plugins/apple/ZappPushPluginsSDK.podspec.json
plugins/zapp-push-plugins/apple/universal/ZPPushProvider.swift
plugins/zapp-push-plugins/package.json

BREAKING CHANGE: Migration for ZappAnalyticsPluginsSDK and ZappPushPluginsSDK

BREAKING CHANGE: Migration for ZappAnalyticsPluginsSDK and ZappPushPluginsSDK

---

plugins/zapp-analytics-plugin-akamai/apple/ZappAnalyticsPluginAkamai.podspec.json
plugins/zapp-analytics-plugin-akamai/apple/ios/APAkamaiClient.h
plugins/zapp-analytics-plugin-akamai/apple/ios/APAkamaiClient.m
plugins/zapp-analytics-plugin-akamai/apple/ios/APAnalyticsProviderAkamai+PlayerObserverProtocol.swift
plugins/zapp-analytics-plugin-akamai/apple/ios/APAnalyticsProviderAkamai.swift
plugins/zapp-analytics-plugin-akamai/apple/ios/ZappAnalyticsPluginAkamai.h
plugins/zapp-analytics-plugin-akamai/manifests/ios_for_quickbrick.json
plugins/zapp-analytics-plugin-akamai/manifests/manifest.config.js
plugins/zapp-analytics-plugin-akamai/package.json
plugins/zapp-analytics-plugin-comscore/apple/ZappAnalyticsPluginComScore.podspec.json
plugins/zapp-analytics-plugin-comscore/apple/ios/APAnalyticsProviderComScore+PlayerObserverProtocol.swift
plugins/zapp-analytics-plugin-comscore/apple/ios/APAnalyticsProviderComScore.swift
plugins/zapp-analytics-plugin-comscore/apple/ios/SteamSense/APStreamSenseManager.h
plugins/zapp-analytics-plugin-comscore/apple/ios/SteamSense/APStreamSenseManager.m
plugins/zapp-analytics-plugin-comscore/apple/ios/ZappAnalyticsPluginComScore.h
plugins/zapp-analytics-plugin-comscore/manifests/ios_for_quickbrick.json
plugins/zapp-analytics-plugin-comscore/manifests/manifest.config.js
plugins/zapp-analytics-plugin-comscore/package.json

adding ComScore analytics and Akamai analytics plugins

feat: ComScore analytics + Akamai analytics plugins

---

plugins/zapp-apple/apple/universal/RootController/RootController.swift

fix for main thread crash on ZappApple

fix: main thread crash on ZappApple

---

plugins/zapp-analytics-plugin-adobe/apple/ZappAnalyticsPluginAdobe.podspec.json
plugins/zapp-analytics-plugin-adobe/apple/ios/APAnalyticsProviderAdobe+AdobeAnalyticsDelegate.swift
plugins/zapp-analytics-plugin-adobe/apple/ios/APAnalyticsProviderAdobe+PlayerObserverProtocol.swift
plugins/zapp-analytics-plugin-adobe/apple/ios/APAnalyticsProviderAdobe.swift
plugins/zapp-analytics-plugin-adobe/apple/ios/AdobeAnalytics.h
plugins/zapp-analytics-plugin-adobe/apple/ios/AdobeAnalytics.m
plugins/zapp-analytics-plugin-adobe/apple/ios/ZappAnalyticsPluginAdobe.h
plugins/zapp-analytics-plugin-adobe/manifests/ios_for_quickbrick.json
plugins/zapp-analytics-plugin-adobe/manifests/manifest.config.js
plugins/zapp-analytics-plugin-adobe/package.json

feat: Add Adobe analytics plugin

---

plugins/quick-brick-xray/android/build.gradle
plugins/quick-brick-xray/android/src/main/java/com/applicaster/plugin/xray/XRayPlugin.kt
plugins/quick-brick-xray/android/src/main/res/values/strings.xml
plugins/quick-brick-xray/manifests/manifest.config.js
plugins/quick-brick-xray/package.json

Improve Android x-ray UI behavior for large log files and introduce log file size limit (all based on x-ray 0.0.22).

feat: tune x-ray UI for large logs

---

plugins/session-storage-idfa/apple/Podfile
plugins/session-storage-idfa/apple/ZappSessionStorageIdfa.podspec.json
plugins/session-storage-idfa/apple/legacy/ZPSessionStorageIdfa.swift
plugins/session-storage-idfa/apple/universal/ZPSessionStorageIdfa.swift
plugins/session-storage-idfa/manifests/ios_for_quickbrick.json
plugins/session-storage-idfa/manifests/manifest.config.js
plugins/session-storage-idfa/manifests/tvos_for_quickbrick.json
plugins/session-storage-idfa/package.json

Add Session Storage IDFA plugin

feat: Add Session Storage IDFA plugin

---

plugins/quick-brick-xray/android/src/main/java/com/applicaster/plugin/xray/XRayPlugin.kt
plugins/quick-brick-xray/manifests/manifest.config.js
plugins/quick-brick-xray/package.json

Now click on the notifications opens x-Ray UI Activity.

feat: default notification intent opens x-ray UI

---

plugins/quick-brick-apple-user-activity/package.json
plugins/quick-brick-apple-user-activity/src/AppleUserActivity.ts

add activity removal on player close

feat: add activity removal on player close

---

plugins/quick-brick-apple-user-activity/__tests__/index.test.ts
plugins/quick-brick-apple-user-activity/package.json

Create version 1.0.0 for the plugin

BREAKING CHANGE: Create version 1.0.0

---

plugins/quick-brick-apple-user-activity/apple/AppleUserActivity.podspec.json
plugins/quick-brick-apple-user-activity/apple/Universal/Bridge/AppleUserActivityBridge.swift

Adding user activity logs on screen present/dismiss

chore: Adding user activity logs on screen present/dismiss

---

plugins/quick-brick-apple-user-activity/apple/Universal/Bridge/AppleUserActivityBridge.swift
plugins/quick-brick-apple-user-activity/manifests/manifest.config.js

chore: updates to user activity

---

plugins/zapp-core/apple/universal/FacadeConnector/FacadeConnector.swift
plugins/zapp-core/apple/universal/FacadeConnector/Protocols/FacadeConnectorOfflineContentProtocol.swift

Adding support for fetching offline item url

chore: Adding support for fetching offline item url

---

plugins/quick-brick-xray/apple/Universal/KeysHelper.swift
plugins/quick-brick-xray/apple/Universal/QuickBrickXray+PluginURLHandlerProtocol.swift
plugins/quick-brick-xray/apple/Universal/QuickBrickXray+Settings.swift
plugins/quick-brick-xray/apple/Universal/QuickBrickXray.swift
plugins/quick-brick-xray/apple/Universal/Settings.swift
plugins/quick-brick-xray/apple/Universal/ViewControllers/SettingsViewController/SettingsHelper.swift
plugins/quick-brick-xray/apple/Universal/ViewControllers/SettingsViewController/SettingsViewController.swift
plugins/quick-brick-xray/apple/ios/FloatingButton.swift
plugins/quick-brick-xray/apple/ios/QuickBrickXray+FloatingButton.swift
plugins/quick-brick-xray/apple/ios/QuickBrickXray+Shortcuts.swift
plugins/zapp-apple/apple/universal/Helpers/LoggerAssistance/LoggerAssistanceManager.swift
plugins/zapp-apple/apple/universal/Helpers/SettingsBunlde/SettingsBundleHelper.swift
plugins/zapp-apple/apple/universal/Helpers/UrlScheme/UrlSchemeHandler+settings.swift
plugins/zapp-apple/apple/universal/Helpers/XrayLogger/Templates/LoggerAssistanceManagerLogs.swift

feat: create xray floating button

---

plugins/quick-brick-xray/apple/ios/FloatingButton.swift
plugins/quick-brick-xray/apple/ios/QuickBrickXray+FloatingButton.swift

pulling constraints fo the button and updating when dragging is ended

fix: pulling constraints fo the button and updating when dragging is ended

---

plugins/zapp-push-plugin-firebase/android/build.gradle
plugins/zapp-push-plugin-firebase/manifests/manifest.config.js

Android min SDK was not updated

fix: min zapp SDK

---

plugins/firebase-base-settings/manifests/manifest.config.js
plugins/firebase-base-settings/package.json
plugins/zapp-push-plugin-firebase/apple/ios/APPushProviderFirebase.swift
plugins/zapp-push-plugin-firebase/manifests/manifest.config.js

Adding Firebase base settings plugin
Updating firebase version to 7.3.0

feat: Adding Firebase base settings plugin + updating version to 7.3.0

---

plugins/applicaster-di-manager/apple/Podfile
plugins/applicaster-di-manager/apple/ZappDiManager.podspec.json
plugins/applicaster-di-manager/apple/universal/ZPDiManager.swift
plugins/applicaster-di-manager/manifests/manifest.config.js
plugins/applicaster-di-manager/package.json

feat: Adding di manager plugin

---

plugins/zapp-apple/apple/universal/Helpers/SwiftUtils/TimeoutTimer.swift
plugins/zapp-apple/apple/universal/Helpers/XrayLogger/Templates/PluginsManager/CrashlogsPluginsManager/CrashlogsPluginsManagerLogs.swift
plugins/zapp-apple/apple/universal/Helpers/XrayLogger/Templates/PluginsManager/GeneralPluginsManager/GeneralPluginsManagerLogs.swift
plugins/zapp-apple/apple/universal/Plugins/Analytics/AnalyticsManager.swift
plugins/zapp-apple/apple/universal/Plugins/CrashLogs/CrashlogsPluginsManager.swift
plugins/zapp-apple/apple/universal/Plugins/General/GeneralPluginsManager.swift
plugins/zapp-apple/apple/universal/Plugins/PluginManagerBase/PluginManagerBase.swift
plugins/zapp-apple/apple/universal/Plugins/PushPluginsManager/PushPluginsManager.swift

Add timeout on plugins initialization
video:
https://slack-files.com/T03GFQLL8-F01K8DKTN02-c9069060da

feat: Add timeout on plugins initialization

---

plugins/firebase-base-settings/manifests/manifest.config.js
plugins/zapp-push-plugin-firebase/apple/ios/APPushProviderFirebase.swift

update firebase back to 6.25.0

feat: revert firebase to 6.25.0

---

plugins/applicaster-di-manager/apple/universal/ZPDiManager.swift
plugins/quick-brick-xray/apple/Universal/QuickBrickXray.swift

chore: Add default context params

---

plugins/zapp-apple/apple/ios/ViewControllers/SplashViewController.swift
plugins/zapp-apple/apple/universal/RootController/RootController+AppLoadingStateMachineDataSource.swift
plugins/zapp-apple/apple/universal/RootController/RootController.swift

fix for app loading when internet access is restored

fix for app loading when internet access is restored

---

plugins/zapp-generic-chromecast/manifests/manifest.config.js

Add placeholder for chromecast param

chore: add placeholder for chromecast param

---

plugins/zapp-react-native-theo-player/apple/universal/THEOplayerView+Convert.swift
plugins/zapp-react-native-theo-player/src/Services/DRM/index.ts
plugins/zapp-react-native-theo-player/src/index.tsx

Add support of DRM.
Parser from Zapp Entry to Theoplayer DRM API.
Data taken from Zapp Entry from path `exstensions/drm`

Add DRM support

---

plugins/quick-brick-xray/manifests/manifest.config.js
plugins/quick-brick-xray/package.json

On Android, dependency was not upgraded in manifest.js

feat: update xray Android manifest dep to 0.1.7

---

plugins/zapp-apple/apple/universal/RootController/FacadeConnector/RootController+FacadeConnectorAnalyticsProtocol.swift
plugins/zapp-core/apple/universal/FacadeConnector/FacadeConnector.swift
plugins/zapp-core/apple/universal/FacadeConnector/Protocols/FacadeConnectorAnalyticsProtocol.swift

adding analytics back to connector as deprecated

adding analytics back to connector as deprecated

---

plugins/zapp-apple/apple/universal/RootController/FacadeConnector/RootController+FacadeConnectorConnectivityProtocol.swift
plugins/zapp-apple/apple/universal/RootController/RootController+ReachabilityManagerDelegate.swift
plugins/zapp-apple/apple/universal/RootController/RootController.swift
plugins/zapp-core/apple/universal/FacadeConnector/Protocols/FacadeConnectorConnnectivityProtocol.swift

adding connectivity listeners deprecation

adding connectivity listeners deprecation

---

plugins/zapp-apple/apple/universal/Plugins/Analytics/AnalyticsManager+EventsBus.swift
plugins/zapp-apple/apple/universal/RootController/RootController+AppLoadingStateMachineDataSource.swift
plugins/zapp-apple/apple/universal/RootController/RootController+ReachabilityManagerDelegate.swift
plugins/zapp-core/apple/universal/EventsBus/EventsBus.swift
plugins/zapp-core/apple/universal/EventsBus/Topics/EventsBusTopic.swift
plugins/zapp-core/apple/universal/EventsBus/Topics/TopicEvents/EventsBusTopic+AnalyticsTopicSubjects.swift
plugins/zapp-generic-chromecast/apple/ios/ChromecastAnalytics.swift
plugins/zapp-generic-chromecast/apple/ios/Extensions/ChromecastAdapter+GeneralProviderProtocol.swift

adding changes to events bus to support custom event and its properties
> {
"type" : "com.example.someevent",
"source" : "/mycontext/4",
"id" : "B234-1234-1234",
"time" : "2018-04-05T17:31:00Z",
"subject": "com.example.subject"
"data": {....},
}

chore: adding changes to events bus to support custom event and its properties

---

plugins/zapp-analytics-plugin-adobe/apple/universal/APAnalyticsProviderAdobe+AdobeAnalyticsDelegate.swift
plugins/zapp-analytics-plugin-adobe/apple/universal/APAnalyticsProviderAdobe+EventsBusTopics.swift
plugins/zapp-apple/apple/universal/Helpers/LoggerAssistance/LoggerAssistanceManager.swift
plugins/zapp-core/apple/universal/EventsBus/EventsBus.swift

Remove unused code
Updates for warnings

chore: Remove unused code

---

plugins/quick-brick-xray/__tests__/event.test.ts
plugins/quick-brick-xray/__tests__/logger-native.test.ts
plugins/quick-brick-xray/__tests__/logger.test.ts
plugins/quick-brick-xray/src/Event.ts
plugins/quick-brick-xray/src/console.ts
plugins/quick-brick-xray/src/index.ts
plugins/quick-brick-xray/src/utils.ts
plugins/quick-brick-xray/types/index.d.ts

This PR prevents issues related to error logs causing crashes and not being reported correctly through Xray

fix: handling of JS errors in Xray

---

plugins/zapp-apple/apple/universal/Plugins/Analytics/AnalyticsManager+EventsBus.swift
plugins/zapp-apple/apple/universal/RootController/RootController+AppLoadingStateMachineDataSource.swift
plugins/zapp-apple/apple/universal/RootController/RootController+ReachabilityManagerDelegate.swift
plugins/zapp-core/apple/universal/EventsBus/EventsBus.swift
plugins/zapp-core/apple/universal/EventsBus/Types/EventsBusType.swift
plugins/zapp-core/apple/universal/EventsBus/Types/PredefinedTypes/EventsBusPredefinedType+AnalyticsSubtypes.swift
plugins/zapp-core/apple/universal/EventsBus/Types/PredefinedTypes/EventsBusPredefinedType.swift
plugins/zapp-generic-chromecast/apple/ios/ChromecastAnalytics.swift
plugins/zapp-generic-chromecast/apple/ios/Extensions/ChromecastAdapter+GeneralProviderProtocol.swift

chore: Updates for eventsbus

---

plugins/zapp-apple/apple/universal/Helpers/NetworkRequests/NetworkRequestsManager.swift

Network request validations to prevent crash

fix: Network request validations to prevent crash

---

plugins/quick-brick-xray/manifests/manifest.config.js

update xray plugin to have min sdk 4.1.0

chore: update xray plugin to have min sdk 4.1.0

---

plugins/zapp-analytics-plugin-segment/apple/universal/SegmentAnalytics.swift
plugins/zapp-analytics-plugin-segment/apple/universal/SegmentAnalyticsHelper.m
plugins/zapp-analytics-plugin-segment/manifests/manifest.config.js

Update segment analytics blacklisted events

chore: Update segment analytics blacklisted events

---

plugins/zapp-analytics-plugin-appsflyer/apple/ZappAnalyticsPluginAppsFlyer.podspec.json
plugins/zapp-analytics-plugin-appsflyer/manifests/manifest.config.js

Appsflyer - add support for SKAdNetworks

Appsflyer skad

---

plugins/zapp-analytics-plugin-appsflyer-strict/manifests/manifest.config.js
plugins/zapp-analytics-plugin-appsflyer-strict/package.json
plugins/zapp-analytics-plugin-appsflyer/apple/ZappAnalyticsPluginAppsFlyer.podspec.json

Add AppsFlyer Strict framework usage for kids apps
https://support.appsflyer.com/hc/en-us/articles/207032066#additional-apis-strict-mode-sdk

feat: Add AppsFlyer Strict framework usage for kids apps

---

plugins/zapp-apple/apple/tests/universal/PluginManager/PluginManagerTests.swift
plugins/zapp-apple/apple/universal/Helpers/NetworkRequests/NetworkRequestsManager.swift

possible fix for removeValueForKey (EXC_BAD_ACCESS (code=EXC_I386_GPFLT))

fix network request crash - removeValueForKey (EXC_BAD_ACCESS (code=EXC_I386_GPFLT))

---

plugins/zapp-analytics-plugin-gemius/apple/universal/GemiusAnalytics+AdEvents.swift
plugins/zapp-react-native-theo-player/apple/universal/ReactNative/THEOplayerViewBridge.m
plugins/zapp-react-native-theo-player/apple/universal/THEOplayerView+Listeners.swift

Gemius+TheoPlayer - add ad events

chore: Gemius+TheoPlayer - add ad events

---

plugins/zapp-analytics-plugin-gemius/android/src/main/java/com/applicaster/analytics/gemius/GemiusAgent.kt

fix: Gemius Android fixes

---

plugins/zapp-analytics-plugin-gemius/apple/universal/GemiusAnalytics+AdEvents.swift
plugins/zapp-analytics-plugin-gemius/apple/universal/GemiusAnalytics+PlayerEvents.swift
plugins/zapp-analytics-plugin-gemius/apple/universal/GemiusAnalytics.swift

chore: Updates for the Gemius

---

plugins/applicaster-cmp-didomi/android/src/main/java/com/applicaster/plugin/didomi/DidomiPlugin.kt
plugins/applicaster-cmp-didomi/apple/ZappCMPDidomi.podspec.json
plugins/applicaster-cmp-didomi/apple/universal/DidomiCMP+EventListeners.swift
plugins/applicaster-cmp-didomi/apple/universal/DidomiCMP.swift

Didomi - Save session storage params

chore: Didomi - Save session storage params

---

plugins/zapp-react-native-theo-player/android/src/main/java/com/theoplayerreactnative/PluginHelper.kt
plugins/zapp-react-native-theo-player/android/src/main/java/com/theoplayerreactnative/TheoPlayerViewManager.java
plugins/zapp-react-native-theo-player/apple/universal/THEOplayerView.swift
plugins/zapp-react-native-theo-player/manifests/manifest.config.js

feat: add additional css option

---

plugins/zapp-apple/apple/universal/Helpers/XrayLogger/Templates/AppDelegateLogs.swift
plugins/zapp-core/apple/universal/Extensions/Image/Image+Extension.swift
plugins/zapp-core/apple/universal/Extensions/String/String+Extension.swift

Prepare local push on silent push notification

chore: Prepare local push on silent push notification

---

plugins/zapp-analytics-plugin-gemius/android/src/main/java/com/applicaster/analytics/gemius/AnalyticsPlayerAdapter.kt
plugins/zapp-analytics-plugin-gemius/android/src/main/java/com/applicaster/analytics/gemius/GemiusAgent.kt
plugins/zapp-analytics-plugin-gemius/apple/universal/GemiusAnalytics+AdEvents.swift
plugins/zapp-analytics-plugin-gemius/apple/universal/GemiusAnalytics+AnalyticsProviderProtocol.swift
plugins/zapp-analytics-plugin-gemius/apple/universal/GemiusAnalytics+PlayerEvents.swift
plugins/zapp-react-native-theo-player/src/Analytics/index.js

fix: update gemius params

---

plugins/zapp-apple/apple/universal/Helpers/RemoteConfiguration/RemoteConfigurationHelper.swift
plugins/zapp-apple/apple/universal/Helpers/UserInterfaceLayerManager/UserInterfaceLayerManager.swift
plugins/zapp-apple/apple/universal/Plugins/PushPluginsManager/PushPluginManager+FacadeConnectorPushProtocol.swift

Updates to localization selected language and push tags

chore: Updates to localization selected language and push tags

---

plugins/quick-brick-opta-stats/android/src/main/java/com/applicaster/opta/statsscreenplugin/PluginConfigurationHandler.kt
plugins/quick-brick-opta-stats/android/src/main/java/com/applicaster/opta/statsscreenplugin/reactnative/OptaBridge.kt
plugins/quick-brick-opta-stats/android/src/main/res/layout/fragment_match_details.xml
plugins/quick-brick-opta-stats/android/src/main/res/layout/fragment_player.xml
plugins/quick-brick-opta-stats/android/src/main/res/layout/fragment_squad.xml
plugins/quick-brick-opta-stats/android/src/main/res/layout/item_away_player_team.xml
plugins/quick-brick-opta-stats/android/src/main/res/layout/item_home_player_team.xml
plugins/quick-brick-opta-stats/android/src/main/res/layout/item_match.xml
plugins/quick-brick-opta-stats/android/src/main/res/layout/item_match_in_all_matches.xml
plugins/quick-brick-opta-stats/android/src/main/res/layout/item_player_squad.xml
plugins/quick-brick-opta-stats/android/src/main/res/layout/item_player_squad_to_the_right.xml
plugins/quick-brick-opta-stats/android/src/main/res/values/styles.xml

Fixing minor layout issues for smaller screens.

fix: tweak COPA Android layouts

---

package.json
plugins/zapp-core/apple/universal/Extensions/Array/Array+Extension.swift
plugins/zapp-push-plugin-firebase/apple/ios/APPushProviderFirebase.swift
plugins/zapp-push-plugin-firebase/manifests/manifest.config.js
plugins/zapp-push-plugin-firebase/package.json
yarn.lock

set localization for default topics in push plugin

feat: set localization for default topics in push plugin

---

plugins/zapp-apple/apple/universal/RootController/RootController.swift

update states order - add plugin step dependency of remote config

update states order - add plugin step dependency of remote config

---

plugins/zapp-apple/apple/universal/Helpers/UserInterfaceLayerManager/UserInterfaceLayerManager.swift
plugins/zapp-apple/apple/universal/RootController/RootController+AppLoadingStateMachineDataSource.swift
plugins/zapp-apple/apple/universal/RootController/RootController.swift

fix for loading interface layer after setting correct language

fix for loading interface layer after setting correct language

---

plugins/zapp-apple/apple/universal/Helpers/NetworkRequests/NetworkRequestsManager.swift

Try to resolve the crash on debug env

fix: Try to resolve the crash on debug env

---

plugins/zapp-apple/apple/universal/Helpers/UrlScheme/UrlSchemeHandler+plugin.swift
plugins/zapp-apple/apple/universal/Helpers/UrlScheme/UrlSchemeHandler.swift

chore: update plugin url handling

---

plugins/quick-brick-opta-stats/android/src/main/java/com/applicaster/opta/statsscreenplugin/screens/home/adapters/MatchAdapter.kt
plugins/quick-brick-opta-stats/android/src/main/java/com/applicaster/opta/statsscreenplugin/utils/ModelUtils.kt

Use app wide locale for plugin

feat: take display locale

---

plugins/first-time-user-expirience-screen/src/Components/FirstTimeUserExpirience/index.tsx

Similar to #291 but now using react third party lib, and padding.

fix: android tablet padding

---

plugins/zapp-analytics-plugin-firebase/apple/ios/APAnalyticsProviderFirebase+AppLoadingHookProtocol.swift
plugins/zapp-analytics-plugin-firebase/apple/ios/APAnalyticsProviderFirebase+AppTrackingTransparency.swift
plugins/zapp-analytics-plugin-firebase/apple/ios/APAnalyticsProviderFirebase.swift
plugins/zapp-analytics-plugin-firebase/manifests/manifest.config.js

add ATT request for firebase analytics

feat: add ATT request for firebase analytics

---

plugins/firebase-base-settings/manifests/manifest.config.js
plugins/zapp-push-plugin-firebase/apple/ZappPushPluginFirebase.podspec.json

adding an option to prevent setting specific version of firebase that adding usage of IDFA

feat: adding an option to prevent setting specific version of firebase that adding usage of IDFA

---

plugins/zapp-push-plugin-firebase/apple/ZappPushPluginFirebase.podspec.json

fix for missing google utilities pod

fix for missing google utilities pod

---

plugins/quick-brick-opta-stats/android/README.md
plugins/quick-brick-opta-stats/android/src/main/java/com/applicaster/opta/statsscreenplugin/OptaStatsContract.kt
plugins/quick-brick-opta-stats/android/src/main/java/com/applicaster/opta/statsscreenplugin/PluginConfigurationHandler.kt
plugins/quick-brick-opta-stats/android/src/main/java/com/applicaster/opta/statsscreenplugin/reactnative/OptaBridge.kt
plugins/quick-brick-opta-stats/android/src/main/java/com/applicaster/opta/statsscreenplugin/utils/ModelUtils.kt
plugins/quick-brick-opta-stats/android/src/main/java/com/applicaster/opta/statsscreenplugin/utils/PluginUtils.kt
plugins/quick-brick-opta-stats/apple/universal/Source/OptaStats+HandleUrlScheme.swift
plugins/quick-brick-opta-stats/apple/universal/Source/OptaStats.swift

update for copa-stats url params

update for copa-stats url params

---

plugins/zapp-react-native-theo-player/src/Analytics/index.js
plugins/zapp-react-native-theo-player/src/Utils/const.ts
plugins/zapp-react-native-theo-player/src/index.tsx

This PR attempts to fix close event, it was not firing on unmount / close button. 
Not it should work and it shouldn't fire unnecessarily.
[![Image from Gyazo](https://i.gyazo.com/8024c828b9a95bdd089e1f777f048a99.png)](https://gyazo.com/8024c828b9a95bdd089e1f777f048a99)
My aggressive linter made several changes to the code.
Started using constants for event names.

fix: close event on unmount, linting fixes, constants

---

plugins/zapp-react-native-theo-player/src/index.tsx

This is a continuation, because the other branch does not let me push this up.

fix: theoplayer tsc errors (2 of 2)

---

plugins/zapp-apple/apple/ios/ViewControllers/SplashViewController.swift

fix to continue with the app loading if splash video fails to play

fix to continue with the app loading if splash video fails to play

---

plugins/applicaster-cmp-didomi/apple/universal/DidomiCMP+EventListeners.swift

Didomi - change to flow to save agree to all even if ATT not confirmed

feat: Didomi - change to flow to save agree to all even if ATT not confirmed

---

plugins/zapp-push-plugin-firebase/android/build.gradle
plugins/zapp-react-native-theo-player/android/build.gradle

- replacing kotlin std lib with universal one
- adding version pull from root project (useless until we add it to SDK though)
- bumping kotlin std lib fallback version to 1.3.50
- fixing version androidx.core:core-ktx to 1.3.1

bump kotlin to 1.3.50 and pull from root project

---

plugins/zapp-react-native-theo-player/src/Services/DRM/index.ts
plugins/zapp-react-native-theo-player/src/THEOplayerView.tsx
plugins/zapp-react-native-theo-player/src/index.tsx

- drm was not returned.
- certificateURL key had wrong name
- fairplay used wrong key for license server url
- drm is expected inside the source, not on the top level (I keep both for now)

fix theo drm transform

---

plugins/quick-brick-xray/manifests/manifest.config.js
plugins/quick-brick-xray/package.json

Bump xray to the version with additional RN data validation

feat: bump xray to 0.2.1

---

plugins/zapp-react-native-theo-player/src/index.tsx

We need StatusBar RN component to hide it properly.

fix: apply StatusBar on RN

---

plugins/session-storage-idfa/apple/legacy/SessionStorageIdfa+ZPAppLoadingHookProtocol.swift
plugins/session-storage-idfa/apple/universal/SessionStorageIdfa+AppLoadingHookProtocol.swift

save temp value for idfa if att is not authorized

save temp value for idfa if att is not authorized

---

plugins/quick-brick-opta-stats/android/src/main/java/com/applicaster/opta/statsscreenplugin/reactnative/OptaPackage.kt
plugins/quick-brick-opta-stats/android/src/main/java/com/applicaster/opta/statsscreenplugin/reactnative/OptaStatsView.kt
plugins/quick-brick-opta-stats/android/src/main/java/com/applicaster/opta/statsscreenplugin/reactnative/OptaTeamView.kt
plugins/quick-brick-opta-stats/android/src/main/java/com/applicaster/opta/statsscreenplugin/reactnative/OptaTeamViewManager.kt
plugins/quick-brick-opta-stats/apple/universal/Bridge/OptaTeamContainer.swift
plugins/quick-brick-opta-stats/apple/universal/Bridge/OptaTeamContainerManagerBridge.swift
plugins/quick-brick-opta-stats/apple/universal/Bridge/OptaTeamContainerManagerBridgeExport.m
plugins/quick-brick-opta-stats/apple/universal/Source/OptaStats.swift
plugins/quick-brick-opta-stats/package.json
plugins/quick-brick-opta-stats/src/index.js

We had to export teams screens to RN component.
Android bridge is done, RN side is done, now we need iOS version.
View name OptaTeamView with property team (not async, no promise)

feat: react wrapped team screen

---

plugins/quick-brick-opta-stats/android/src/main/java/com/applicaster/opta/statsscreenplugin/OptaStatsContract.kt

Logo url was before part of screen data params, not config. Take it from the config now

fix: url logo was not taken from params

---

plugins/quick-brick-opta-stats/android/src/main/java/com/applicaster/opta/statsscreenplugin/reactnative/OptaStatsView.kt
plugins/quick-brick-opta-stats/android/src/main/java/com/applicaster/opta/statsscreenplugin/screens/home/HomeFragment.kt
plugins/quick-brick-opta-stats/android/src/main/java/com/applicaster/opta/statsscreenplugin/screens/home/adapters/GroupAdapter.kt
plugins/quick-brick-opta-stats/android/src/main/res/values/dimens.xml

Home screen tweaks:
- set all matches first
- fit 5 teams

fix: android UI tweaks

---

plugins/applicaster-cmp-didomi/apple/universal/DidomiCMP+AppTrackingTransparency.swift

didomi: moving att to main thread

fix: moving att to main thread

---

plugins/quick-brick-opta-stats/apple/universal/Screens/MatchesCollectionView.swift

refactor all matches to be first in the list

chore: refactor all matches to be first in the list

---

plugins/applicaster-cmp-didomi/apple/universal/DidomiCMP+EventListeners.swift

Fix didimi stuck that causing not send completion on all required events
https://user-images.githubusercontent.com/6761714/122994553-97b8bb80-d376-11eb-99ac-af24ea0677c2.MP4

chore: fix didomi stuck on selection of the items

---

plugins/zapp-analytics-plugin-gemius/android/src/main/java/com/applicaster/analytics/adapters/AnalyticsPlayerAdapter.kt
plugins/zapp-analytics-plugin-gemius/android/src/main/java/com/applicaster/analytics/adapters/AnalyticsScreenAdapter.kt
plugins/zapp-analytics-plugin-gemius/android/src/main/java/com/applicaster/analytics/adapters/IAnalyticsAdapter.kt
plugins/zapp-analytics-plugin-gemius/android/src/main/java/com/applicaster/analytics/gemius/GemiusAgent.kt
plugins/zapp-analytics-plugin-gemius/android/src/main/java/com/applicaster/analytics/gemius/PlayerAdapter.kt
plugins/zapp-analytics-plugin-gemius/android/src/main/java/com/applicaster/analytics/gemius/ScreenAdapter.kt
plugins/zapp-analytics-plugin-gemius/apple/universal/GemiusAnalytics+AdEvents.swift
plugins/zapp-analytics-plugin-gemius/apple/universal/GemiusAnalytics+AnalyticsProviderProtocol.swift
plugins/zapp-analytics-plugin-gemius/apple/universal/GemiusAnalytics+ScreenEvents.swift
plugins/zapp-analytics-plugin-gemius/apple/universal/GemiusAnalytics.swift

Basic screen and nav event analitycs reporting.
Events we have are not perfect, so probably we want to add new events for this later.

feat: Analytics screen event routing

---

plugins/quick-brick-native-apple/apple/tvos/Views/ParallaxView/Other/ParallaxableView.swift
plugins/quick-brick-opta-stats/apple/universal/Screens/MatchesCollectionView.swift
plugins/quick-brick-xray/apple/Universal/Cells/SwitchCell/SwitchCellDelegate.swift
plugins/quick-brick-xray/apple/Universal/ViewControllers/SettingsViewController/SettingsViewController.swift

Updates for deprecations in Xcode 13

chore: Updates for deprecations in Xcode 13

---

plugins/quick-brick-opta-stats/apple/universal/Screens/TeamCardViewController.swift

fix to optastats player presentation from QB pushed screen

fix to optastats player presentation from QB pushed screen

---

plugins/quick-brick-opta-stats/android/src/main/java/com/applicaster/opta/statsscreenplugin/screens/matchdetails/adapter/PlayerGoalAdapter.kt
plugins/quick-brick-opta-stats/android/src/main/res/values/colors.xml
plugins/quick-brick-opta-stats/apple/universal/Screens/MatchDetailViewController.swift
plugins/quick-brick-opta-stats/apple/universal/Screens/SharedModels.swift

feat: highlight own goals in red

---

plugins/zapp-apple/apple/universal/Plugins/PushPluginsManager/PushPluginManager+FacadeConnectorPushProtocol.swift
plugins/zapp-apple/apple/universal/RootController/FacadeConnector/RootController+FacadeConnectorLocalNotificationProtocol.swift
plugins/zapp-apple/apple/universal/RootController/FacadeConnector/RootController+FacadeConnectorPushProtocol.swift
plugins/zapp-core/apple/universal/FacadeConnector/FacadeConnector.swift
plugins/zapp-core/apple/universal/FacadeConnector/Protocols/FacadeConnectorLocalNotificationProtocol.swift
plugins/zapp-core/apple/universal/FacadeConnector/Protocols/FacadeConnectorPushProtocol.swift

Refactor to support completion block Result

feat: Refactor to support completion block Result

---

plugins/zapp-apple/apple/universal/Plugins/PushPluginsManager/PushPluginManager+FacadeConnectorPushProtocol.swift
plugins/zapp-apple/apple/universal/RootController/FacadeConnector/RootController+FacadeConnectorLocalNotificationProtocol.swift
plugins/zapp-apple/apple/universal/RootController/FacadeConnector/RootController+FacadeConnectorPushProtocol.swift
plugins/zapp-core/apple/universal/FacadeConnector/Protocols/FacadeConnectorLocalNotificationProtocol.swift
plugins/zapp-core/apple/universal/FacadeConnector/Protocols/FacadeConnectorPushProtocol.swift

fix for result completion deprecations

fix for result completion deprecations

---

plugins/zapp-apple/apple/universal/Plugins/PluginManager/PluginsManager+LoadingStateMachineDataSource.swift
plugins/zapp-apple/apple/universal/RootController/RootController+AppLoadingStateMachineDataSource.swift
plugins/zapp-apple/apple/universal/RootController/RootController.swift

to allow it to run in parallel to splash screen before presenting the hooks

chore: Move plugins remote configuration to separate state

---

plugins/zapp-apple/apple/tests/universal/PluginManager/PluginManagerTests.swift
plugins/zapp-apple/apple/universal/Plugins/PluginManager/PluginsManager.swift
plugins/zapp-apple/apple/universal/RootController/RootController+AppLoadingStateMachineDataSource.swift

chore: Remove unused function

---

plugins/zapp-react-native-theo-player/android/src/main/java/com/theoplayerreactnative/TheoPlayerViewModule.java

Enable WebView debugging in Theo player plugin in debug builds.

feat: enable WebView debugging in debug

---

plugins/applicaster-cmp-didomi/android/build.gradle
plugins/applicaster-cmp-didomi/android/src/main/java/com/applicaster/plugin/didomi/DidomiPlugin.kt
plugins/applicaster-cmp-didomi/manifests/manifest.config.js

Migrating to new consent plugins flow.

feat: new consent plugings api

---

plugins/quick-brick-opta-stats/apple/universal/Bridge/OptaBridge.swift
plugins/quick-brick-opta-stats/apple/universal/Screens/GroupCardsTableView.swift
plugins/quick-brick-opta-stats/apple/universal/Screens/GroupCardsViewController.swift
plugins/quick-brick-opta-stats/apple/universal/Screens/KnockoutGroupCardsViewController.swift
plugins/quick-brick-opta-stats/apple/universal/Screens/MatchListingTableViewCell.swift
plugins/quick-brick-opta-stats/apple/universal/Screens/MatchesCardViewController.swift
plugins/quick-brick-opta-stats/apple/universal/Screens/MatchesCardViewModel.swift
plugins/quick-brick-opta-stats/apple/universal/Screens/MatchesCollectionView.swift
plugins/quick-brick-opta-stats/apple/universal/Screens/MatchesTableView.swift
plugins/quick-brick-opta-stats/apple/universal/Source/Localized.swift
plugins/quick-brick-opta-stats/apple/universal/Source/OptaStats.swift
plugins/quick-brick-opta-stats/apple/universal/UI/MatchListingTableViewCell.xib
plugins/quick-brick-opta-stats/apple/universal/UI/StatsViewControllers.storyboard
plugins/quick-brick-opta-stats/manifests/manifest.config.js

Create new knockout stats screen
verified by Nico

feat: Create new knockout stats screen

---

plugins/quick-brick-native-apple/apple/ios/ReactNative/PushBridge.swift
plugins/zapp-apple/apple/universal/Plugins/PushPluginsManager/PushPluginManager+FacadeConnectorPushProtocol.swift
plugins/zapp-apple/apple/universal/RootController/FacadeConnector/RootController+FacadeConnectorPushProtocol.swift
plugins/zapp-core/apple/universal/FacadeConnector/Protocols/FacadeConnectorPushProtocol.swift
plugins/zapp-core/apple/universal/Plugins/Push/Protocols/PushProviderProtocol.swift

Adding push plugins error handling

feat: Adding push plugins error handling

---

plugins/zapp-analytics-plugin-gemius/android/src/main/java/com/applicaster/analytics/gemius/GemiusAgent.kt
plugins/zapp-analytics-plugin-gemius/apple/universal/GemiusAnalytics.swift

Set both plugin-scope and global user agent string.
Later we should either add SDK constant and check for override, or remove global one

feat: set gemius user agent string

---

plugins/quick-brick-native-apple/apple/ios/ReactNative/QuickBrickViewController.swift

set initial orientation per device type

fix: set initial orientation per device type

---

plugins/zapp-apple/apple/universal/RootController/FacadeConnector/RootController+FacadeConnectorConnectivityProtocol.swift

Related task: https://applicaster.monday.com/boards/1141653998/pulses/1437512866
In order to make autoplay working when both wifi and cellular connections are on, we need to return .wifi connection type in that case.

fix: made connectivity state to be .wifi when both wifi and cellular connections are on

---

plugins/zapp-analytics-plugin-segment/apple/universal/SegmentAnalytics+CustomLifecycleEvents.swift
plugins/zapp-analytics-plugin-segment/apple/universal/SegmentAnalytics.swift
plugins/zapp-apple/apple/universal/RootController/FacadeConnector/RootController+FacadeConnectorAppDataProtocol.swift
plugins/zapp-core/apple/universal/EventsBus/Types/PredefinedTypes/EventsBusPredefinedType.swift
plugins/zapp-core/apple/universal/FacadeConnector/Protocols/FacadeConnectorAppDataProtocol.swift

add custom applaunch event to segment analytics plugin

fix: add custom applaunch event to segment analytics plugin

---

plugins/zapp-analytics-plugin-segment/android/build.gradle

Bump segment library to latest version. It reports events when enabled, independent of the activity hooks, that solves CMP issue.

feat: bump segment to 4.10.0

---

plugins/remote-info-to-session-storage/apple/universal/ZPRemoteInfoToSessionStorage.swift

fix for remote info completion handlers

fix for remote info completion handlers

---

plugins/applicaster-cmp-didomi/apple/universal/DidomiCMP.swift
plugins/applicaster-cmp-onetrust/apple/universal/OneTrustCmp.swift
plugins/applicaster-di-manager/apple/universal/ZPDiManager.swift
plugins/remote-info-to-session-storage/apple/universal/ZPRemoteInfoToSessionStorage.swift

fix for providers protocols

---

plugins/zapp-apple/apple/universal/Helpers/XrayLogger/Templates/PluginsManager/PluginsManagerLogs.swift
plugins/zapp-apple/apple/universal/Plugins/PluginManager/PluginsManager+LoadingStateMachineDataSource.swift
plugins/zapp-apple/apple/universal/Plugins/PluginManager/PluginsManager.swift
plugins/zapp-apple/apple/universal/Plugins/PluginManager/UserInterfaceLayerDependantPluginsSubManager/UserInterfaceLayerDependantPluginsSubManager+LoadingStateMachineDataSource.swift
plugins/zapp-apple/apple/universal/Plugins/PluginManager/UserInterfaceLayerDependantPluginsSubManager/UserInterfaceLayerDependantPluginsSubManager.swift
plugins/zapp-apple/apple/universal/RootController/RootController+AppLoadingStateMachineDataSource.swift

Update to uiLayer dependent plugins
creating sub manager to handle additional loading states and completions based on plugins

fix: Update to uiLayer dependent plugins

---

plugins/applicaster-cmp-onetrust/apple/ZappCmpOneTrust.podspec.json

Update to OneTrust version with the fix to initial focus

fix: Update to OneTrust version with the fix to initial focus

---

plugins/quick-brick-google-ima-apple/apple/ZappGoogleInteractiveMediaAds.podspec.json
plugins/quick-brick-google-ima-apple/apple/universal/GoogleInteractiveMediaAdsAdapter/GoogleInteractiveMediaAdsAdapter+IMAAdsLoaderDelegate.swift
plugins/quick-brick-google-ima-apple/apple/universal/GoogleInteractiveMediaAdsAdapter/GoogleInteractiveMediaAdsAdapter+IMALinkOpenerDelegate.swift

Ticket: https://applicaster.monday.com/boards/1139872912/pulses/1541485524
Bump IMA Version for iOS to 3.14.4
Resume ads when user clicks show more button and goes back

feat: bump IMA version for iOS 3.14.4

---

plugins/zapp-generic-chromecast/apple/ios/Bridge/Chromecast/RNEventEmitter.swift

fix to chromecast emitter

---

plugins/quick-brick-xray/package.json

breaking: bump x-ray version

---

plugins/zapp-generic-chromecast/apple/ios/Extensions/ChromecastAdapter+ChromecastExtendedPlayerControlsProtocol.swift

Related task: https://applicaster.monday.com/boards/1141653998/pulses/1512954333. Detailed description of fix is provided in updates section inside the ticket.
Behaviour after fix: 
https://user-images.githubusercontent.com/76045389/128012062-4d5dcbba-b409-4cfe-bb94-c5703e3990a9.MP4
Behaviour before fix:
https://user-images.githubusercontent.com/76045389/128012122-4fddf5b5-6b04-486e-9e16-46e6aa91050d.MP4

fix: changed presentation style for casting screen to fullscreen

---

plugins/applicaster-cmp-didomi/android/src/main/java/com/applicaster/plugin/didomi/DidomiPlugin.kt

Fixing and updating assorted issues for offline startup flow.
- Didomi

fix offline mode

---

plugins/zapp-push-plugin-urban-airship/android/src/main/java/com/app/urbanairshippushplugin/UrbanAirshipPushProvider.java
plugins/zapp-push-plugin-urban-airship/android/src/main/java/com/app/urbanairshippushplugin/reciver/PluginAirshipReceiver.java
plugins/zapp-push-plugin-urban-airship/apple/Podfile
plugins/zapp-push-plugin-urban-airship/apple/ZappPushPluginUrbanAirship.podspec.json

Fix deep link handling for Airship plugin
Improve logging of Airship plugin

feat: fix deeplinking in Airship pushes

---

plugins/quick-brick-native-apple/apple/ios/ReactNative/QuickBrickViewController.swift

Ticket: https://applicaster.monday.com/boards/1139872912/pulses/1562495241
Issue happens when RN is sending default landscape orientation. 
And user has landscape left orientation. Application force to set landscape right that cause rotation jump
Bad: 
https://user-images.githubusercontent.com/6761714/128941189-bc3f7546-5255-466a-b116-745fc9bb4788.mp4
Good:
https://user-images.githubusercontent.com/6761714/128941596-6997975c-8e15-4d3a-9aa1-9cf9c5357faa.mov

Resolve default landscape orientation

---

plugins/quick-brick-user-account-ui-component/manifests/styles.config.js

Refactor manifest keys for user account ui component

chore: fix manufest for user account component

---

.circleci/config.yml
fastlane/Fastfile
plugins/zapp-core/apple/universal/EventsBus/Types/EventsBusType.swift
plugins/zapp-core/apple/universal/EventsBus/Types/PredefinedTypes/EventsBusPredefinedType+Player.swift
plugins/zapp-core/apple/universal/EventsBus/Types/PredefinedTypes/EventsBusPredefinedType.swift
plugins/zapp-core/apple/universal/Plugins/Analytics/BaseProvider/AnalyticsBaseProvider+AnalyticsProviderProtocol.swift
plugins/zapp-core/apple/universal/Plugins/Analytics/BaseProvider/AnalyticsBaseProvider.swift
plugins/zapp-core/apple/universal/Plugins/Analytics/Events/AdAnalyticsEvent.swift
plugins/zapp-core/apple/universal/Plugins/Analytics/Events/PlayerAnalyticsEvent.swift
plugins/zapp-core/apple/universal/Plugins/Analytics/Events/ScreenAnalyticsEvent.swift
plugins/zapp-core/apple/universal/Plugins/Analytics/Handlers/AnalyticsAdEventsHandler.swift
plugins/zapp-core/apple/universal/Plugins/Analytics/Handlers/AnalyticsBaseEventsHandler.swift
plugins/zapp-core/apple/universal/Plugins/Analytics/Handlers/AnalyticsEventsHandlerProtocol.swift
plugins/zapp-core/apple/universal/Plugins/Analytics/Handlers/AnalyticsPlayerEventsHandler.swift
plugins/zapp-core/apple/universal/Plugins/Analytics/Handlers/AnalyticsScreenEventsHandler.swift
plugins/zapp-core/apple/universal/Plugins/Analytics/Media/AnalyticsPlayerMediaObject.swift
scripts/test_tasks/index.js

Adding player events to be able to use with new analytics infra

chore: Adding the player events

---

plugins/zapp-core/apple/universal/Plugins/Analytics/BaseProvider/AnalyticsBaseProvider.swift
plugins/zapp-core/apple/universal/Plugins/Analytics/Events/AdAnalyticsEvent.swift
plugins/zapp-core/apple/universal/Plugins/Analytics/Handlers/AnalyticsAdEventsHandler.swift
plugins/zapp-core/apple/universal/Plugins/Analytics/Handlers/AnalyticsEventsHandlerProtocol.swift
plugins/zapp-core/apple/universal/Plugins/Analytics/Handlers/AnalyticsPlayerEventsHandler.swift

chore: add support for new ad events

---

plugins/quick-brick-user-account-ui-component/index.d.ts
plugins/quick-brick-user-account-ui-component/manifests/amazon_fire_tv_for_quickbrick.json
plugins/quick-brick-user-account-ui-component/manifests/android_for_quickbrick.json
plugins/quick-brick-user-account-ui-component/manifests/android_tv_for_quickbrick.json
plugins/quick-brick-user-account-ui-component/manifests/ios_for_quickbrick.json
plugins/quick-brick-user-account-ui-component/manifests/lg_tv.json
plugins/quick-brick-user-account-ui-component/manifests/samsung_tv.json
plugins/quick-brick-user-account-ui-component/manifests/tvos_for_quickbrick.json
plugins/quick-brick-user-account-ui-component/package.json
plugins/quick-brick-user-account-ui-component/src/components/Button/ButtonTV.android.tsx
plugins/quick-brick-user-account-ui-component/src/components/UserAccount/LoginFlow.android.tsx

If merged this will fix the focus on android tv

Fix/ua UI component focus android

---

plugins/quick-brick-native-apple/apple/universal/ReactNative/ReactNativeCommunicationModule.swift
plugins/quick-brick-native-apple/apple/universal/ReactNative/ReactNativeManager.swift

Exposed `acadeConnector.connector?.uiLayer?.setPrefersHomeIndicatorAutoHidden` to react-native through the QB Communiaction Module

feat(QB-App): added setPrefersHomeIndicatorAutoHidden to communication module
